version: '3'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=redis:redis
    ports:
      - "8081:8081"

  eureka-server:
    image: eureka-server
    container_name: eureka-server
    build:
      context: ""
      dockerfile: eurekaServer/Dockerfile
    ports:
      - "8761:8761"

  zuul-server:
    image: zuul-server
    container_name: zuul-server
    restart: on-failure
    depends_on:
      - eureka-server
    build:
      context: ""
      dockerfile: zuulServer/Dockerfile
    ports:
      - "9010:9010"

  users-service:
    image: users-service
    container_name: users-service
    depends_on:
      - zuul-server
    environment:
      - SPRING_REDIS_HOST=redis
    build:
      context: ""
      dockerfile: usersService/Dockerfile
    ports:
      - "8001:8001"

  tasks-service:
    image: tasks-service
    container_name: tasks-service
    depends_on:
      - zuul-server
    environment:
      - SPRING_REDIS_HOST=redis
    build:
      context: ""
      dockerfile: tasksService/Dockerfile
    ports:
      - "8000:8000"
