server:
  port: ${PORT:8000} # Indicate the default PORT where this service will be started

spring:
  application:
    name: tasks-service #current service name to be used by the eureka server
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/taskService;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          lob:
            non_contextual_creation: true
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://eureka-server:8761}/eureka/
