spring:
  application:
    name: eureka-server # current service name
  port: 5000
  cloud:
    config:
      server:
        git:
          uri: https://github.com/artembelmeha/taskTracker/tree/master/config
          name:
