info:
  component: eureka-server
server:
  port: ${PORT:8761} # Indicate the default PORT where this service will be started
eureka:
  instance:
    hostname: eureka-server
  client:
    registerWithEureka: false # telling the server not to register himself in the service registry
    fetchRegistry: false
